Es features done
viktoroman/andersen-js-course pull request #1
Opened 2019-06-03 23:57 UTC by viktoroman

The "es-features" part is done.
The "array-practice" part is done.

2019-06-04 09:23 UTC, volvachev requested changes

2019-06-04 09:23 UTC, volvachev commented on src/array-practice/task5.js
> +      const currValue = itr.next();
Можешь деструктурировать результат вызова next, чтобы сразу получить done и value.

2019-06-04 09:23 UTC, volvachev commented on src/array-practice/task7.js
> +  return arr.slice( 0, (amount < 0 ? 0 : amount) );
У тебя скорее всего выключен приттер, убери пробелы после скобок.
```
arr.slice(0, (amount < 0 ? 0 : amount));
```

2019-06-04 09:23 UTC, volvachev commented on src/es-features/task4.js
> +  [`baz${(() => {return 'test';})()}`]: 'new field'
Функция должна быть определенна выше, откажись от самовызывающийся функции.

2019-06-04 09:23 UTC, volvachev commented on src/array-practice/task3.js
> +export const forEachRight = (arr, cb) => { arr.reverse().forEach(cb); };
reverse мутирует исходный массив, используй reverse на новом массиве.

2019-06-04 09:23 UTC, volvachev commented on src/array-practice/task4.js
> +export const union = (arr1, arr2) => new Set([...arr1, ...arr2]);
Ты возвращаешь объект Set, а должен вернуть массив.

2019-06-04 09:23 UTC, volvachev commented on src/es-features/task6.js
> +    isActive: isActive = false,
Убери rename property на тоже самое имя.

2019-06-04 09:23 UTC, volvachev commented on src/es-features/task9.js
> +    [22, 1, 90, 70].filter( (x) => x < 3 )[0]
Воспользуйся новым методом массива из es6.

2019-06-04 23:15 UTC, viktoroman commented
Правки согласно пожеланиям внесены.
Код отформатирован подобающим образом.

2019-06-08 11:07 UTC, volvachev requested changes

2019-06-08 11:07 UTC, volvachev commented on src/array-practice/task1.js
> +  if (typeof cb === 'function') return arr.some(cb);
Либо параметр по умолчанию для функции.
Либо сделай тернарник для функции.
для примера
```
const callback = typeof cb === 'function' ? cb  : defaultFunction;
```

2019-06-08 11:52 UTC, viktoroman commented on src/array-practice/task1.js
> +  if (typeof cb === 'function') return arr.some(cb);
Пофиксил.
Выбрал вариант с тернарником.

2019-06-12 12:08 UTC, merged